# Generated by Django 5.1.2 on 2024-10-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_portal', '0002_rename_request_date_servicerequest_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('issue_from_customer', 'Issue from Customer Side')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='service_category',
            field=models.CharField(choices=[('Gas Delivery and Distribution', 'Gas Delivery and Distribution'), ('Customer Service and Billing', 'Customer Service and Billing'), ('Safety and Compliance', 'Safety and Compliance'), ('Infrastructure Maintenance and Upgrades', 'Infrastructure Maintenance and Upgrades'), ('Environmental Stewardship', 'Environmental Stewardship')], max_length=100),
        ),
    ]
